/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessageRouteImport } from './routes/message'
import { Route as LuckyDrawRouteImport } from './routes/lucky-draw'
import { Route as FreeCashRouteImport } from './routes/free-cash'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as BonusTaskRouteImport } from './routes/bonus-task'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InvestmentIdRouteImport } from './routes/investment.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAiCreateRouteImport } from './routes/admin.ai-create'
import { Route as ApiPublicHooksPaystackRouteImport } from './routes/api/public/hooks/paystack'
import { Route as ApiPublicHooksGenerateProofRouteImport } from './routes/api/public/hooks/generate-proof'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const LuckyDrawRoute = LuckyDrawRouteImport.update({
  id: '/lucky-draw',
  path: '/lucky-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeCashRoute = FreeCashRouteImport.update({
  id: '/free-cash',
  path: '/free-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusTaskRoute = BonusTaskRouteImport.update({
  id: '/bonus-task',
  path: '/bonus-task',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InvestmentIdRoute = InvestmentIdRouteImport.update({
  id: '/investment/$id',
  path: '/investment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiCreateRoute = AdminAiCreateRouteImport.update({
  id: '/ai-create',
  path: '/ai-create',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksPaystackRoute = ApiPublicHooksPaystackRouteImport.update({
  id: '/api/public/hooks/paystack',
  path: '/api/public/hooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateProofRoute =
  ApiPublicHooksGenerateProofRouteImport.update({
    id: '/api/public/hooks/generate-proof',
    path: '/api/public/hooks/generate-proof',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bonus-task': typeof BonusTaskRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/free-cash': typeof FreeCashRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/message': typeof MessageRoute
  '/orders': typeof OrdersRoute
  '/recharge': typeof RechargeRoute
  '/team': typeof TeamRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/ai-create': typeof AdminAiCreateRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/investment/$id': typeof InvestmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/generate-proof': typeof ApiPublicHooksGenerateProofRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bonus-task': typeof BonusTaskRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/free-cash': typeof FreeCashRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/message': typeof MessageRoute
  '/orders': typeof OrdersRoute
  '/recharge': typeof RechargeRoute
  '/team': typeof TeamRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/ai-create': typeof AdminAiCreateRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/investment/$id': typeof InvestmentIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/generate-proof': typeof ApiPublicHooksGenerateProofRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bonus-task': typeof BonusTaskRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/free-cash': typeof FreeCashRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/message': typeof MessageRoute
  '/orders': typeof OrdersRoute
  '/recharge': typeof RechargeRoute
  '/team': typeof TeamRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/ai-create': typeof AdminAiCreateRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/investment/$id': typeof InvestmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/generate-proof': typeof ApiPublicHooksGenerateProofRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bonus-task'
    | '/certification'
    | '/chat'
    | '/free-cash'
    | '/lucky-draw'
    | '/message'
    | '/orders'
    | '/recharge'
    | '/team'
    | '/wallet'
    | '/withdraw'
    | '/admin/ai-create'
    | '/admin/banners'
    | '/admin/investments'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/investment/$id'
    | '/admin/'
    | '/api/public/hooks/generate-proof'
    | '/api/public/hooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bonus-task'
    | '/certification'
    | '/chat'
    | '/free-cash'
    | '/lucky-draw'
    | '/message'
    | '/orders'
    | '/recharge'
    | '/team'
    | '/wallet'
    | '/withdraw'
    | '/admin/ai-create'
    | '/admin/banners'
    | '/admin/investments'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/investment/$id'
    | '/admin'
    | '/api/public/hooks/generate-proof'
    | '/api/public/hooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bonus-task'
    | '/certification'
    | '/chat'
    | '/free-cash'
    | '/lucky-draw'
    | '/message'
    | '/orders'
    | '/recharge'
    | '/team'
    | '/wallet'
    | '/withdraw'
    | '/admin/ai-create'
    | '/admin/banners'
    | '/admin/investments'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/investment/$id'
    | '/admin/'
    | '/api/public/hooks/generate-proof'
    | '/api/public/hooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BonusTaskRoute: typeof BonusTaskRoute
  CertificationRoute: typeof CertificationRoute
  ChatRoute: typeof ChatRoute
  FreeCashRoute: typeof FreeCashRoute
  LuckyDrawRoute: typeof LuckyDrawRoute
  MessageRoute: typeof MessageRoute
  OrdersRoute: typeof OrdersRoute
  RechargeRoute: typeof RechargeRoute
  TeamRoute: typeof TeamRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  InvestmentIdRoute: typeof InvestmentIdRoute
  ApiPublicHooksGenerateProofRoute: typeof ApiPublicHooksGenerateProofRoute
  ApiPublicHooksPaystackRoute: typeof ApiPublicHooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucky-draw': {
      id: '/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/lucky-draw'
      preLoaderRoute: typeof LuckyDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-cash': {
      id: '/free-cash'
      path: '/free-cash'
      fullPath: '/free-cash'
      preLoaderRoute: typeof FreeCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-task': {
      id: '/bonus-task'
      path: '/bonus-task'
      fullPath: '/bonus-task'
      preLoaderRoute: typeof BonusTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/investment/$id': {
      id: '/investment/$id'
      path: '/investment/$id'
      fullPath: '/investment/$id'
      preLoaderRoute: typeof InvestmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-create': {
      id: '/admin/ai-create'
      path: '/ai-create'
      fullPath: '/admin/ai-create'
      preLoaderRoute: typeof AdminAiCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/paystack': {
      id: '/api/public/hooks/paystack'
      path: '/api/public/hooks/paystack'
      fullPath: '/api/public/hooks/paystack'
      preLoaderRoute: typeof ApiPublicHooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-proof': {
      id: '/api/public/hooks/generate-proof'
      path: '/api/public/hooks/generate-proof'
      fullPath: '/api/public/hooks/generate-proof'
      preLoaderRoute: typeof ApiPublicHooksGenerateProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiCreateRoute: typeof AdminAiCreateRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiCreateRoute: AdminAiCreateRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BonusTaskRoute: BonusTaskRoute,
  CertificationRoute: CertificationRoute,
  ChatRoute: ChatRoute,
  FreeCashRoute: FreeCashRoute,
  LuckyDrawRoute: LuckyDrawRoute,
  MessageRoute: MessageRoute,
  OrdersRoute: OrdersRoute,
  RechargeRoute: RechargeRoute,
  TeamRoute: TeamRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  InvestmentIdRoute: InvestmentIdRoute,
  ApiPublicHooksGenerateProofRoute: ApiPublicHooksGenerateProofRoute,
  ApiPublicHooksPaystackRoute: ApiPublicHooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
